### ISSUE TITLE
What is the preferred way for runnig this project?

### ISSUE THREAD

**Issue by categulario** [SyntaxRules/Terminal-Snake#1]
I just cloned it and I'm not sure how to run this. I tried `python terminalsnake` but it complains about the relative imports. Then I tried to `cd` into de directory and then run `python __main__.py` with a similar result.

I'm using python 3.6

Of course with some minor changes I managed to run the code

![captura de pantalla de 2018-06-06 23-45-23](https://user-images.githubusercontent.com/790756/41078688-d482cce0-69e3-11e8-93c5-0f8f8b313b77.png)

**Comment by categulario** [comment]
would be resolved by #2

**Comment by SyntaxRules** [comment]
For others landing here, @categulario added this to the README.md. The perferred method for running this is: `python -m terminalsnake`

Thanks for your contribution, feel free to add more!
